/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author ebers
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CambioAceite = new javax.swing.JButton();
        servicioGeneral = new javax.swing.JButton();
        lavado = new javax.swing.JButton();
        VentaRepuesto = new javax.swing.JButton();
        ventaDeProducto = new javax.swing.JButton();
        Agenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        CambioAceite.setBackground(new java.awt.Color(255, 51, 0));
        CambioAceite.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        CambioAceite.setText("Cambio De Aceite");
        CambioAceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioAceiteActionPerformed(evt);
            }
        });
        getContentPane().add(CambioAceite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        servicioGeneral.setBackground(new java.awt.Color(255, 51, 0));
        servicioGeneral.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        servicioGeneral.setText("Servicio General");
        servicioGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(servicioGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 170, 170, 30));

        lavado.setBackground(new java.awt.Color(255, 51, 0));
        lavado.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lavado.setText("Lavado Y Aspirado");
        lavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lavadoActionPerformed(evt);
            }
        });
        getContentPane().add(lavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, 30));

        VentaRepuesto.setBackground(new java.awt.Color(255, 51, 0));
        VentaRepuesto.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        VentaRepuesto.setText("Venta De Reuestos");
        VentaRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaRepuestoActionPerformed(evt);
            }
        });
        getContentPane().add(VentaRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 170, 30));

        ventaDeProducto.setBackground(new java.awt.Color(255, 51, 0));
        ventaDeProducto.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        ventaDeProducto.setText("Venta De Productos");
        ventaDeProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaDeProductoActionPerformed(evt);
            }
        });
        getContentPane().add(ventaDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        Agenda.setBackground(new java.awt.Color(255, 51, 0));
        Agenda.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        Agenda.setText("Agenda");
        Agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendaActionPerformed(evt);
            }
        });
        getContentPane().add(Agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 253, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaagenes/taller3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 729, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambioAceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioAceiteActionPerformed
        
        CambioAceite cambio = new CambioAceite();
        cambio.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_CambioAceiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void servicioGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioGeneralActionPerformed
       
        ServicioGeneral servicio = new ServicioGeneral();
        servicio.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_servicioGeneralActionPerformed

    private void lavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lavadoActionPerformed
        
        Lavado lavado = new Lavado();
        lavado.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_lavadoActionPerformed

    private void ventaDeProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaDeProductoActionPerformed
        
        VentaAticulo articulo = new VentaAticulo();
        articulo.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_ventaDeProductoActionPerformed

    private void VentaRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaRepuestoActionPerformed
        
        VentaRepuesto repuesto = new VentaRepuesto();
        repuesto.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_VentaRepuestoActionPerformed

    private void AgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendaActionPerformed
        
        Agenda agenda = new Agenda();
        agenda.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_AgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agenda;
    private javax.swing.JButton CambioAceite;
    private javax.swing.JButton VentaRepuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lavado;
    private javax.swing.JButton servicioGeneral;
    private javax.swing.JButton ventaDeProducto;
    // End of variables declaration//GEN-END:variables
}
